version: 2.0
jobs:
 build:
   machine: true
   working_directory: ~/Plan2Task-BackEnd
   steps:
     - checkout
     - run: docker-compose stop
     - run: docker-compose build
     - run: docker-compose up -d
     - deploy:
          name: Run docker finish
          command: |
            echo "finish"
     