version: 2.0
jobs:
 build:
   machine: 
     services:
      - docker
   working_directory: ~/Plan2Task-BackEnd
   steps:
     - checkout
     - run: git pull
     - run: docker-compose down
     - run: docker-compose build
     - run: docker-compose up -d
   deployment:
     production:
          branch: master
          commands:
               - bin/push.sh