version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker-compose stop
      - run: docker system prune
      - run: docker system prune -a
      - run: docker-compose build