version: 2.0
jobs:
 build:
   machine: true
   working_directory: ~/Plan2Task-BackEnd
   steps:
     - checkout
     - run:
          command: 'sudo docker-compose stop'
     - run:
          command: 'sudo docker-compose build'
     - run:
          command: 'sudo docker-compose up -d'
     