version: 2.0
jobs:
 build:
   machine: 
     services:
      - docker
   working_directory: ~/Plan2Task-BackEnd
   steps:
     - checkout
     - run:
        name: ssh
        command: ssh -i gc_plan2task_app tozzis@35.198.252.173
     - run: docker-compose down
     - run: docker-compose build
     - run: docker-compose up -d
   deployment:
     production:
          branch: master
          command:
               - bin/push.sh