version: 2.0
jobs:
  build:
    machine: 
      services:
        - docker
    working_directory: ~/Plan2Task-BackEnd
    steps:
      - checkout
      - run: docker-compose down
      - run: docker-compose build
      - run: docker-compose up -d
  deploy:
    machine: true
    working_directory: ~/Plan2Task-BackEnd
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - $fingerprint
      - run:
          name: Deploy Plan2Task
          command: |
            ssh $SSH_USER@$SSH_HOST  \
            '
              cd /var/Plan2Task-BackEnd;
              sudo docker-compose down
              sudo git pull;
              sudo docker-compose build;
              sudo docker-compose up -d;
            '