version: 2.0
jobs:
 build:
   machine: 
     services:
      - docker
   working_directory: ~/Plan2Task-BackEnd
   steps:
     - run:
        name: ssh login
        commands: 'ssh -i ~/.ssh/gc_plan2task_app tozzis@35.198.252.173'
     - checkout
     - run: docker-compose down
     - run: docker-compose build
     - run: docker-compose up -d
   deployment:
     production:
          branch: master
          commands:
               - bin/push.sh